services:
  postgresTESTE:
    image: postgres:16
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: minha_senha
      POSTGRES_DB: meu_banco
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
