AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template para serviços ECS'

Parameters:
  ECSCluster:
    Type: String
  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
  APIServiceName:
    Type: String  
  
  ChatbotServiceName:
    Type: String  

  APITaskDefinition:
    Type: String
  ChatbotTaskDefinition:
    Type: String

  APISecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  ChatbotSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
  APITargetGroup:
    Type: String
  ChatbotTargetGroup:
    Type: String
  ECSServiceRole:
    Type: String

Resources:
  APIService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref APITaskDefinition
      ServiceName: !Sub ${APIServiceName}-service
      DesiredCount: 1
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref APISecurityGroup
          Subnets:
            - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2
      LoadBalancers:
        - TargetGroupArn: !Ref APITargetGroup
          ContainerName: api-container
          ContainerPort: 8000


  APIScalableTarget:
    DependsOn: APIService
    Type: AWS::ApplicationAutoScaling::ScalableTarget
    Properties:
      MaxCapacity: 3  # ou outro valor máximo desejado
      MinCapacity: 0  # ou outro valor mínimo desejado
      ResourceId: !Sub service/${ECSCluster}/${APIServiceName}-service
      RoleARN: !Ref ECSServiceRole
      ScalableDimension: ecs:service:DesiredCount
      ServiceNamespace: ecs

  APIScalingPolicy:
    DependsOn: APIScalableTarget
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: CpuScalingPolicy
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref APIScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ECSServiceAverageCPUUtilization
        TargetValue: 50.0  # Alvo de utilização de CPU em %
        ScaleInCooldown: 60
        ScaleOutCooldown: 60

  ChatbotService:
    DependsOn: APIService
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ChatbotTaskDefinition
      ServiceName: !Sub ${ChatbotServiceName}-service
      DesiredCount: 1
      LaunchType: FARGATE
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 50
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !Ref ChatbotSecurityGroup
          Subnets:
            - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2
      LoadBalancers:
        - TargetGroupArn: !Ref ChatbotTargetGroup
          ContainerName: chatbot-container
          ContainerPort: 8001