AWSTemplateFormatVersion: '2010-09-09'
Description: Stack raiz que orquestra o serviço ECS com banco de dados
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
  APIServiceName:
    Type: String
    Default: core-api
  APIContainerPort:
    Type: Number
    Default: 8000
  APIContainerImage:
    Type: String
  ChatbotServiceName:
    Type: String
    Default: chatbot
  ChatbotContainerPort:
    Type: Number
    Default: 8001
  ChatbotContainerImage:
    Type: String
  ContainerCpu:
    Type: Number
    Default: 256
  ContainerMemory:
    Type: Number
    Default: 512
  DesiredCount:
    Type: Number
    Default: 2
  ECSTaskExecutionRole:
    Type: String
  ECSTaskRole:
    Type: String
  SecretKey:
    Type: String
    Description: Chave secreta para assinatura de tokens JWT
  AccessTokenExpireHours:
    Type: Number
    Default: 24
Resources:
  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/infraestrutura-projeto-integrador-perosa/91277fc83a88dfb9ad5bbdefc82f6d10.template
      Parameters:
        VpcId:
          Ref: VpcId
        APIContainerPort:
          Ref: APIContainerPort
        ChatbotContainerPort:
          Ref: ChatbotContainerPort
  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/infraestrutura-projeto-integrador-perosa/d41ce52c3da78cf28fe13bf7078e69a3.template
      Parameters:
        VpcId:
          Ref: VpcId
        PrivateSubnet1:
          Ref: PrivateSubnet1
        PrivateSubnet2:
          Ref: PrivateSubnet2
        InstanceName: database-core
        DBSecurityGroup:
          Fn::GetAtt:
          - SecurityGroupsStack
          - Outputs.DBSecurityGroup
  ALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/infraestrutura-projeto-integrador-perosa/1669e172507f06036fe93f26383e01f4.template
      Parameters:
        VpcId:
          Ref: VpcId
        PrivateSubnet1:
          Ref: PrivateSubnet1
        PrivateSubnet2:
          Ref: PrivateSubnet2
        APIContainerPort:
          Ref: APIContainerPort
        ChatbotContainerPort:
          Ref: ChatbotContainerPort
        ALBSecurityGroup:
          Fn::GetAtt:
          - SecurityGroupsStack
          - Outputs.ALBSecurityGroup
  ECSClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.us-east-1.amazonaws.com/infraestrutura-projeto-integrador-perosa/70db3b247284654104f742f656c3b4f3.template
Outputs:
  LoadBalancerDNS:
    Value:
      Fn::GetAtt:
      - ALBStack
      - Outputs.LoadBalancerDNS
  DBHost:
    Value:
      Fn::GetAtt:
      - DatabaseStack
      - Outputs.DBHost
  ECSCluster:
    Value:
      Fn::GetAtt:
      - ECSClusterStack
      - Outputs.ECSCluster
  ChatbotSecurityGroup:
    Value:
      Fn::GetAtt:
      - SecurityGroupsStack
      - Outputs.ChatbotSecurityGroup
  APISecurityGroup:
    Value:
      Fn::GetAtt:
      - SecurityGroupsStack
      - Outputs.APISecurityGroup
  ChatbotTargetGroup:
    Value:
      Fn::GetAtt:
      - ALBStack
      - Outputs.ChatbotTargetGroup
  APITargetGroup:
    Value:
      Fn::GetAtt:
      - ALBStack
      - Outputs.APITargetGroup
