AWSTemplateFormatVersion: '2010-09-09'
Description: Stack raiz que orquestra o serviço ECS com banco de dados

Parameters:
 # Config Rede
  VpcId:
    Type: AWS::EC2::VPC::Id
  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
 
 # Config Services
  APIServiceName:
    Type: String
    Default: core-api
  APIContainerPort:
    Type: Number
    Default: 8000
  APIContainerImage:
    Type: String

  ChatbotServiceName:
    Type: String
    Default: chatbot
  ChatbotContainerPort:
    Type: Number
    Default: 8001
  ChatbotContainerImage:
    Type: String

  ContainerCpu:
    Type: Number
    Default: 256
  ContainerMemory:
    Type: Number
    Default: 512
  DesiredCount:
    Type: Number
    Default: 2
  # Role ECS
  ECSTaskExecutionRole:
    Type: String
  ECSTaskRole:
    Type: String

  # openssl rand -base64 32
  SecretKey:
    Type: String
    Description: Chave secreta para assinatura de tokens JWT

  AccessTokenExpireHours:
    Type: Number
    Default: 24
 

Resources:
  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./stacks/security-groups.yaml
      Parameters:
        VpcId: !Ref VpcId
        APIContainerPort: !Ref APIContainerPort
        ChatbotContainerPort: !Ref ChatbotContainerPort 

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./stacks/database.yaml
      Parameters:
        VpcId: !Ref VpcId
        PrivateSubnet1: !Ref PrivateSubnet1
        PrivateSubnet2: !Ref PrivateSubnet2
        InstanceName: database-core
        DBSecurityGroup: !GetAtt SecurityGroupsStack.Outputs.DBSecurityGroup

  ALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./stacks/alb.yaml
      Parameters:
        VpcId: !Ref VpcId
        PrivateSubnet1: !Ref PrivateSubnet1
        PrivateSubnet2: !Ref PrivateSubnet2
        APIContainerPort: !Ref APIContainerPort
        ChatbotContainerPort: !Ref ChatbotContainerPort
        ALBSecurityGroup: !GetAtt SecurityGroupsStack.Outputs.ALBSecurityGroup

  ECSClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./stacks/ecs/cluster.yaml
Outputs:
  LoadBalancerDNS:
    Value: !GetAtt ALBStack.Outputs.LoadBalancerDNS
  DBHost:
    Value: !GetAtt DatabaseStack.Outputs.DBHost
  ECSCluster:
    Value: !GetAtt ECSClusterStack.Outputs.ECSCluster
 
  ChatbotSecurityGroup:
    Value: !GetAtt SecurityGroupsStack.Outputs.ChatbotSecurityGroup  
  APISecurityGroup:
    Value: !GetAtt SecurityGroupsStack.Outputs.APISecurityGroup
  ChatbotTargetGroup:
    Value: !GetAtt ALBStack.Outputs.ChatbotTargetGroup
  APITargetGroup:
    Value: !GetAtt ALBStack.Outputs.APITargetGroup
  