AWSTemplateFormatVersion: '2010-09-09'
Description: Stack raiz que orquestra o serviço ECS com banco de dados

Parameters:
 # Config Rede
  VpcId:
    Type: AWS::EC2::VPC::Id
  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
 
 # Config Services
  APIServiceName:
    Type: String
    Default: core-api
  APIContainerPort:
    Type: Number
    Default: 8000
  APIContainerImage:
    Type: String

  ChatbotServiceName:
    Type: String
    Default: chatbot
  ChatbotContainerPort:
    Type: Number
    Default: 8001
  ChatbotContainerImage:
    Type: String

  ContainerCpu:
    Type: Number
    Default: 256
  ContainerMemory:
    Type: Number
    Default: 512
  DesiredCount:
    Type: Number
    Default: 2
  # Role ECS
  ECSTaskExecutionRole:
    Type: String
  ECSTaskRole:
    Type: String

Resources:
  SecurityGroupsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./stacks/security-groups.yaml
      Parameters:
        VpcId: !Ref VpcId
        APIContainerPort: !Ref APIContainerPort
        ChatbotContainerPort: !Ref ChatbotContainerPort 

  DatabaseStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./stacks/database.yaml
      Parameters:
        VpcId: !Ref VpcId
        PrivateSubnet1: !Ref PrivateSubnet1
        PrivateSubnet2: !Ref PrivateSubnet2
        InstanceName: database-core
        DBSecurityGroup: !GetAtt SecurityGroupsStack.Outputs.DBSecurityGroup

  ALBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./stacks/alb.yaml
      Parameters:
        VpcId: !Ref VpcId
        PrivateSubnet1: !Ref PrivateSubnet1
        PrivateSubnet2: !Ref PrivateSubnet2
        APIContainerPort: !Ref APIContainerPort
        ChatbotContainerPort: !Ref ChatbotContainerPort
        ALBSecurityGroup: !GetAtt SecurityGroupsStack.Outputs.ALBSecurityGroup

  ECSClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./stacks/ecs/cluster.yaml
  
  ECSTasksStack:
    DependsOn: [ECSClusterStack]
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./stacks/ecs/tasks.yaml
      Parameters:
        APIServiceName: !Ref APIServiceName
        ChatbotServiceName: !Ref ChatbotServiceName
        
        APIContainerImage: !Ref APIContainerImage
        ChatbotContainerImage: !Ref ChatbotContainerImage
        
        APIContainerPort: !Ref APIContainerPort
        ChatbotContainerPort: !Ref ChatbotContainerPort

        ContainerCpu: !Ref ContainerCpu
        ContainerMemory: !Ref ContainerMemory

        ECSTaskRole: !Ref ECSTaskRole
        ECSTaskExecutionRole: !Ref ECSTaskExecutionRole
        DBHost: !GetAtt DatabaseStack.Outputs.DBHost
        ApiUrl: !GetAtt ALBStack.Outputs.LoadBalancerDNS

  ECSServicesStack:
    DependsOn: [ECSTasksStack]
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./stacks/ecs/services.yaml
      Parameters:
        APITaskDefinition: !GetAtt ECSTasksStack.Outputs.APITaskDefinitionArn
        ChatbotTaskDefinition: !GetAtt ECSTasksStack.Outputs.ChatbotTaskDefinitionArn
        PrivateSubnet1: !Ref PrivateSubnet1
        PrivateSubnet2: !Ref PrivateSubnet2 
        APIServiceName: !Ref APIServiceName
        ChatbotServiceName: !Ref ChatbotServiceName
        ECSCluster: !GetAtt ECSClusterStack.Outputs.ECSCluster
        APITargetGroup: !GetAtt ALBStack.Outputs.APITargetGroup
        ChatbotTargetGroup: !GetAtt ALBStack.Outputs.ChatbotTargetGroup
        DesiredCount: !Ref DesiredCount
        ChatbotContainerPort: !Ref ChatbotContainerPort
        APIContainerPort: !Ref APIContainerPort
        APIContainerImage: !Ref APIContainerImage
        ChatbotContainerImage: !Ref ChatbotContainerImage
        APISecurityGroup: !GetAtt SecurityGroupsStack.Outputs.APISecurityGroup
        ChatbotSecurityGroup: !GetAtt SecurityGroupsStack.Outputs.ChatbotSecurityGroup
Outputs:
  LoadBalancerDNS:
    Value: !GetAtt ALBStack.Outputs.LoadBalancerDNS
  DBHost:
    Value: !GetAtt DatabaseStack.Outputs.DBHost
  ECSCluster:
    Value: !GetAtt ECSClusterStack.Outputs.ECSCluster
  APITaskDefinitionArn:
    Value: !GetAtt ECSTasksStack.Outputs.APITaskDefinitionArn
  ChatbotTaskDefinitionArn:
    Value: !GetAtt ECSTasksStack.Outputs.ChatbotTaskDefinitionArn
  ChatbotSecurityGroup:
    Value: !GetAtt SecurityGroupsStack.Outputs.ChatbotSecurityGroup  
  APISecurityGroup:
    Value: !GetAtt SecurityGroupsStack.Outputs.APISecurityGroup
  ChatbotTargetGroup:
    Value: !GetAtt ALBStack.Outputs.ChatbotTargetGroup
  APITargetGroup:
    Value: !GetAtt ALBStack.Outputs.APITargetGroup
  