AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template para criar um cluster ECS'

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: app-cluster
      CapacityProviders:
        - FARGATE
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
Outputs:
  ECSCluster:
    Value: !Ref ECSCluster